version: "3"
services:
  db:
    image: postgres:9.6.8
    restart: always
    environment:
      - PGDATA=/pgdata
    volumes:
      - ./pgdata:/pgdata
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: ./app.dockerfile
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - GEM_HOME=/usr/local/bundle
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - ./bundle:/usr/local/bundle
      - ./app:/app
    tty: true
    stdin_open: true
    command: ./docker-start
